#!/bin/sh
cd /etc/ipsec.d/
mkdir -p private cacerts certs

ipsec pki --gen --type rsa --size 4096 \
    --outform pem > private/strongswanKey.pem
chmod 600 private/strongswanKey.pem

ipsec pki --self --ca --lifetime 3650 \
    --in private/strongswanKey.pem --type rsa \
    --dn "C=FFA, O=FarFarAway, CN=Far Far Away Root CA" \
    --outform pem \
    > cacerts/strongswanCert.pem
ipsec pki --print --in cacerts/strongswanCert.pem

ipsec pki --gen --type rsa --size 2048 \
    --outform pem > private/vpnHostKey.pem
chmod 600 private/vpnHostKey.pem

ipsec pki --pub --in private/vpnHostKey.pem --type rsa | \
    ipsec pki --issue --lifetime 730 \
    --cacert cacerts/strongswanCert.pem \
    --cakey private/strongswanKey.pem \
    --dn "C=FFA, O=FarFarAway, CN=core.poetic.systems" \
    --san core.poetic.systems \
    --flag serverAuth --flag ikeIntermediate \
    --outform pem > certs/vpnHostCert.pem
ipsec pki --print --in certs/vpnHostCert.pem
